spring:
  profiles:
    active: @env@
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
build-info:
  app-name: @project.name@
  app-version: @project.version@
server:
  port: 8080
app:
  log:
    path: works/logs